#Disble FTP, enable the hacky https
CONFIG_FEATURE_WGET_FTP=n
CONFIG_FEATURE_WGET_HTTPS=y

#Unused stuff
CONFIG_LINUXRC=n
CONFIG_MKDOSFS=n
CONFIG_FEATURE_HWIB=n
CONFIG_HDPARM=n
CONFIG_VCONFIG=n
CONFIG_VLOCK=n
CONFIG_UBIRENAME=n
CONFIG_TRACEROUTE=n
CONFIG_TELNET=n
CONFIG_RDATE=n
CONFIG_EJECT=n
CONFIG_MKE2FS=n
CONFIG_MKSWAP=n
CONFIG_SWAPON=n
CONFIG_SWAPOFF=n
CONFIG_LSPCI=n
CONFIG_CHATTR=n
CONFIG_FSCK=n
CONFIG_LSATTR=n
CONFIG_INSMOD=n
CONFIG_LSMOD=n
CONFIG_MODPROBE=n
CONFIG_RMMOD=n
